{% set name = "bloaty" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/google/bloaty/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 682640678a748d043eea65df48831f807d39a1e761eacc461c756256f7ec6a26
    patches:
      - 0001-Don-t-force-C-11.patch
      - 0001-Add-missing-stdexcept-include.patch
  - url: https://github.com/abseil/abseil-cpp/archive/1948f6f967e34db9793cfa8b4bcbaf370d039fd8.tar.gz
    sha256: 4818d1b3f23787cb818da365ad65951b17a0fcb51c41c906056da1d002a4f7f2
    folder: third_party/abseil-cpp
  - url: https://github.com/nico/demumble/archive/01098eab821b33bd31b9778aea38565cd796aa85.tar.gz
    sha256: 1d193dbd50d614a6ab65fdb6fad5240f0092024bb8aac4c75c52311c6ce49635
    folder: third_party/demumble

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libprotobuf 3.21
    - re2
    - libcapstone

test:
  commands:
    - bloaty --help

about:
  home: https://github.com/google/bloaty
  summary: a size profiler for binaries
  license: Apache-2.0
  license_file:
    - LICENSE
    - third_party/abseil-cpp/LICENSE
    - third_party/demumble/LICENSE

extra:
  recipe-maintainers:
    - xhochy
